---
- name: install Apache HTTP Server
  hosts: webservers
  become: yes

  # vars:
  #   http_port: 80
  #   max_clients: 200

  remote_user: root

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest

  - name: write the apache config file
    template:
      src: server-status.conf
      dest: /etc/httpd/conf.d/server-status.conf
    notify:
    - restart apache

  - name: ensure apache is running
    service:
      name: httpd
      state: started

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
